### ISSUE TITLE
Difference in Average Consumption between DV with and without compression

### ISSUE THREAD

**Issue by alexklar** [AMOSus/amos-ss16-proj6#77] opened 2016-07-05 15:59 UTC
Hello guys! Again the issue I posted in the whatsapp group. There is a big difference in the representation of the data with and without the compression. As an example Trace_DV, selected all carriers and opened Average Consumption Graph with dimension Avg. Energy. As you can see with compression we see that carrier 16 has a higher energy consumption and is increasing. This would be great for detecting the contamination but if you compare it to all other carriers without compression it gets completely lost among others and clearly there is no contamination.

![dv with compression avg consumption](https://cloud.githubusercontent.com/assets/18442122/16590939/e91859f0-42d9-11e6-8dec-6c63d7db9508.PNG)

![dv no compression avg consumption](https://cloud.githubusercontent.com/assets/18442122/16590938/e918748a-42d9-11e6-9632-ecb396dd9529.PNG)

**Comment by ghost** [comment] 2016-07-08 18:57
Hello Everyone,

I looked at the data in some test cases to assure that it is processing correctly. These are the problems that i have encountered:

One REAL bug (unintended) that didn’t influence the energy consumption, but only the position. 
0: Timestamps not relative without compression. —> Fixed
The time stamps were not set to relative when no compression was there.

The rest was intended, but leads to influencing the energy consumption average. Nevertheless, I changed the following:

1: No more removing of initial timestamps —> Done
The timestamps (with the low energy consumption under 1400) were removed in the beginning of each iteration, but only after the compression. But without compression it happened that sometimes the energy spiked up to 1400 way earlier than with compression (of course because it is an average) therefore, with compression a lot more is cut away in the beginning. Cutting away before compression also doesn’t make sense, because then only a couple (like 20) timestamps will be cut away, which is also random because the energy may spike above 1400 at any time for only 1 or two timestamps and then stay low for another 1000 timestamps. Therefore, no more cutting away. This influenced the AVG energy because different amounts were cut away (when comparing NO and ANY amount of compression). To make a long story short: we cannot cut this away without being inconsistent.

2: Cutting away the last timestamps BEFORE compression —> Done
The last timestamps, with the huge spikes were cut away after compression. Even though i tried to balance this out by cutting away always around 200 independent of compression (cut away 1 if the compression = 200, cut away 4 if the compression = 50, cut away 200 if no compression) it still isn’t the same as cutting away before. This is now fixed as i always cut away 200 before compressing and thats it. For comparing compression = 100 and compression = 1 this shouldn’t have made a difference, because no rounding was involved.

3: Calculating the average INSIDE the compress initial method —>  Done, but still needs to be written to DB and changed in 
As stated in the meeting, we have problems that sometimes we don’t have all timestamps, because sometimes it is not possible to map them to a drive. For one carrier it looks like this 1, 2, 3, 5, 6, 7, 8 and for the other like this 1, 2, 3, 4, 6, 7, 8. When compressing, the algorithm tries to set them to the same timestamps even though they may be differentt. This is pretty complex and sometimes the algorithm has to make up time stamps where there is no time stamps. This is to make all the time stamps for compression = 100 look like this: 0, 100, 200, 300, 400 etc. If i don’t do it, for one carrier it might look like this: 0, 115, 220, 320, 420 and for the other like this 0, 100, 201, 301, 401 … Since we average after the compressing, and a „100“ in time stamp didn’t actually average over 100 values but maybe over 98 values. Averaging over this timestamps is not correct. Not because the calculation was wrong. When there were only 98 timestamps, the averaging was also done on 98 timestamps in the algorithm. But when averaging later before writing it to the DB the average weights all timestamps the same, which they are not because one might be 98 and the other one might be 100. This will cause a small difference, that is not visible when having clean data. Since the data is really dirty sometimes, this may have an impact. The solution is to average inside the initial compression method, before compressing. The other alternative is to make the data look ugly (like 0, 115, 220, 320, 420 and for the other like this 0, 100, 201, 301, 401).

As of now: 
0 —> Fixed
1 —> Changed
2 —> Changed
3 —> Changed in the algorithm, now every time the same average and total energy consumption is calculated WITHIN the algorithm. Due to the other mentioned problems it will never exactly be the same when calculating it afterwards.
After this is calculated the method „writeEnergyToDatabase(carrier, energy):“ is called, but it needs to be written in to the DB and changed in writeDataToDatabase

I would prefer for @AMOSus  to change this because he did the writeDataToDatabase and the writing stuff to the database stuff.
Therefore TODO for @AMOSus :
-Write the average and total in compressInitialData.py in the method writeEnergyToDatabase(carrier, energy) to the database. All necessary parameters for this are in the comments
-Don’t calculate and transfer the average and total in writeDataToDatabase.py

**Comment by ghost** [comment] 2016-07-08 21:27
Commit 649c014 has all the changes. @AMOSus it would be great if you could get back to me for 3.

**Comment by ghost** [comment] 2016-07-08 21:35
Changes on the continuous graph are already there, note that you will only see changes at the average graph once the writing of the values to the DB has been changed. I will keep you updated.

**Comment by TobiDo** [comment] 2016-07-09 11:06
I will (try to) take care of writing average values to DB.

**Comment by ghost** [comment] 2016-07-10 15:56
Fixed with 3a29255 and 649c014

**Closed as completed by ghost** 2016-07-10 15:56 UTC
Labels: enhancement

**Comment by ghost** [comment] 2016-07-10 15:59
I labeled this as enhancement, because it was not a bug, just a wrong requirement in the past
